language: go

dist: trusty

go:
- 1.8
- 1.9
- "1.10"
- tip

env:
  - DEP_VERSION=0.4.1

cache: apt

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - npm i -g codeclimate-test-reporter

jobs:
  include:
  - stage: test
    script: |
      dep ensure
      go test -race -coverprofile=coverage.out -covermode=atomic .
  - stage: build
    script: |
      cd cmd
      dep ensure
      go build
  - stage: coverage
    script: codeclimate-test-reporter < coverage.out
    if: env(TRAVIS_GO_VERSION) = "1.10"
