[[constraint]]
  name = "github.com/exoscale/egoscale"
  version = "0.9.19"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  version = "0.4.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.33.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
